### PR TITLE
Icaps23

### PR DESCRIPTION
**Pull request by francescofuggitti**
## Proposed changes

This PR covers previous unmerged PRs: #160 and #180.

In this PR:

- Overall cleaning of the package
- Structure the package
- Update dependencies
- Fix docs

There are still missing parts to be added before the official release. Please find them in #246.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/master/CONTRIBUTING.md) doc
- [x] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by LBonassi95** [comment]
Just fixed a small bug: I added the "true" PPLTL symbol to the dictionary with the user-defined mapping.

**Comment by francescofuggitti** [comment]
> Just fixed a small bug: I added the "true" PPLTL symbol to the dictionary with the user-defined mapping.

@LBonassi95 why is the bug? Written like that it's not really self-explanatory. Perhaps, we can fix the bug in a clearer way?

**Comment by LBonassi95** [comment]
Bug: if the user provides a mapping, then the dictionary "self.from_atoms_to_fluent" is used to map the atomic propositions in the formula to the "actual" pddl fluents. If the input ppltl goal contains the atom "true" (representing the truth), then the compiler tries to map "true" to some pddl fluent, and this raises an exception.

Fix: I add the atom "true" to the mapping by default (see line 72 of my commit).

Maybe we can find a better way to fix this.

**Comment by francescofuggitti** [comment]
I'm trying to reproduce the error, but I get it only when the map does not specify the true symbol as well.

For instance, I'm trying the goal `on-b_a & O(true)` with the following map:

```
on-b_a,on b a
true,true
```
on the domain and problem file given under the `examples/` dir of the repo. In this case, the compilation works without any problem. If I remove the `true,true` part in the map file, then I get the error. 

If this is true, I guess that putting `true,true` in the map is the intended behavior, not I bug. The same applies when we want to map predicates with no terms like `emptyhand,emptyhand`.

Is that right? If not, could you please give a minimal reproducible example?

**Comment by francescofuggitti** [comment]
You're right. Then, adding the `true` formula through the mapping or adding it in a hardcoded way are not proper ways to fix the issue. 
We can fix it by handling the true (and false) formula directly within the derived_visitor and the predicates_visitor. 

Let me know if that sounds good.

**Pull request merged**
